@host = localhost
@port = 3000
@apiversion = api/v1

### Recuperar Um Categoria por ID
GET http://{{host}}:{{port}}/{{apiversion}}/categorias/37c4deaf-ac8b-48c5-a472-28d7f1ecb76a


### Recuperar Todas as Categorias
GET http://{{host}}:{{port}}/{{apiversion}}/categorias


### Inserir Uma Categoria### Inserir Uma Categoria
POST http://{{host}}:{{port}}/{{apiversion}}/categorias
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZiN2FmNTgyLTQ1MjAtNDQ0Ni04MTZiLWIxOGM1MWI1OTFkNCIsIm5vbWUiOiJGZXJuYWRhIiwiZW1haWwiOiJmZXJuYWRhQGVtYWlsLmNvbSIsInRpcG8iOiJBRE1JTklTVFJBRE9SIiwiaWF0IjoxNzA0ODQ2MDc2LCJleHAiOjE3MDQ4NDk2NzZ9.8T_XbgcI4er8HgVrZA33lPs37o5dDgQpa2eqO7VIARI

{
    "nome":"Sala de Televisão"
}

### Atualizar Categoria
PUT http://{{host}}:{{port}}/{{apiversion}}/categorias/37c4deaf-ac8b-48c5-a472-28d7f1ecb76a
Content-Type: application/json

{
"id": "37c4deaf-ac8b-48c5-a472-28d7f1ecb76a",
"nome": "Sala de jogos"
}

### Deletar Categoria
DELETE  http://{{host}}:{{port}}/{{apiversion}}/categorias/48e6f5a7-214d-47fb-8766-46c62fab804b